#!/usr/bin/env bash
set -euo pipefail

# ── Claude Code Menu Bar Monitor — Installer ─────────────────────
#
# Creates a pyenv virtualenv (or plain venv), installs dependencies,
# and sets up a launch command.
#
# Usage:
#   chmod +x install.sh
#   ./install.sh
#
# What it does:
#   1. Detects pyenv or falls back to python3 -m venv
#   2. Creates virtualenv "claude-monitor"
#   3. Installs rumps + requests
#   4. Installs the app as a package (editable)
#   5. Creates a launcher script at ~/.local/bin/claude-monitor
#   6. Optionally installs a launchd plist for auto-start at login
# ──────────────────────────────────────────────────────────────────

APP_NAME="claude-monitor"
PYTHON_VERSION="3.12.4"   # pyenv target — adjust if needed
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LAUNCHER="$HOME/.local/bin/claude-monitor"
PLIST_PATH="$HOME/Library/LaunchAgents/com.claude.menubar-monitor.plist"

info()  { printf "\033[1;34m▸\033[0m %s\n" "$*"; }
ok()    { printf "\033[1;32m✔\033[0m %s\n" "$*"; }
warn()  { printf "\033[1;33m⚠\033[0m %s\n" "$*"; }
fail()  { printf "\033[1;31m✖\033[0m %s\n" "$*"; exit 1; }

# ── Step 1: Find or set up Python ────────────────────────────────

VENV_PATH=""
PYTHON_BIN=""

if command -v pyenv &>/dev/null; then
    info "pyenv detected"

    # Check if Python version exists AND was built with framework support
    NEEDS_INSTALL=false
    if ! pyenv versions --bare | grep -q "^${PYTHON_VERSION}$"; then
        NEEDS_INSTALL=true
    else
        # Verify existing install has framework support (required for macOS menu bar)
        PYPREFIX="$(pyenv prefix "$PYTHON_VERSION" 2>/dev/null || echo "")"
        if [ -n "$PYPREFIX" ] && ! "$PYPREFIX/bin/python" -c "import sysconfig; assert 'Python.framework' in sysconfig.get_config_var('prefix') or sysconfig.get_config_var('PYTHONFRAMEWORK')" 2>/dev/null; then
            warn "Python ${PYTHON_VERSION} was built WITHOUT framework support"
            warn "Menu bar apps require --enable-framework. Rebuilding…"
            NEEDS_INSTALL=true
        fi
    fi

    if $NEEDS_INSTALL; then
        info "Installing Python ${PYTHON_VERSION} via pyenv (with --enable-framework)…"
        info "This is required for macOS menu bar apps to display an icon."
        PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install "$PYTHON_VERSION" --force
    else
        ok "Python ${PYTHON_VERSION} (framework build) already installed"
    fi

    # Recreate virtualenv if needed (in case Python was rebuilt)
    if ! pyenv virtualenvs --bare | grep -q "^${APP_NAME}$"; then
        info "Creating pyenv virtualenv '${APP_NAME}'…"
        pyenv virtualenv "$PYTHON_VERSION" "$APP_NAME"
    elif $NEEDS_INSTALL; then
        info "Recreating virtualenv after Python rebuild…"
        pyenv uninstall -f "$APP_NAME"
        pyenv virtualenv "$PYTHON_VERSION" "$APP_NAME"
    else
        ok "pyenv virtualenv '${APP_NAME}' already exists"
    fi

    VENV_PATH="$(pyenv prefix "$APP_NAME")"
    PYTHON_BIN="${VENV_PATH}/bin/python"

else
    warn "pyenv not found — falling back to python3 -m venv"
    info "Using Homebrew or system Python (these are framework builds by default)"

    VENV_PATH="${SCRIPT_DIR}/.venv"
    if [ ! -d "$VENV_PATH" ]; then
        info "Creating venv at ${VENV_PATH}…"
        python3 -m venv "$VENV_PATH"
    fi
    PYTHON_BIN="${VENV_PATH}/bin/python"
fi

ok "Python: ${PYTHON_BIN}"

# ── Step 2: Install the package ──────────────────────────────────

info "Installing dependencies…"
"$PYTHON_BIN" -m pip install --upgrade pip -q
"$PYTHON_BIN" -m pip install -e "$SCRIPT_DIR" -q
ok "Package installed (editable mode)"

# ── Step 3: Verify ───────────────────────────────────────────────

info "Verifying imports…"
"$PYTHON_BIN" -c "import rumps; import requests; print('  rumps', rumps.__version__); print('  requests', requests.__version__)"
ok "All dependencies verified"

# Verify framework build can create menu bar UI
info "Verifying macOS menu bar support…"
if "$PYTHON_BIN" -c "from AppKit import NSApplication; NSApplication.sharedApplication().setActivationPolicy_(1)" 2>/dev/null; then
    ok "AppKit/menu bar support confirmed"
else
    warn "AppKit import failed — menu bar icon may not appear."
    warn "If using pyenv, try:  PYTHON_CONFIGURE_OPTS=\"--enable-framework\" pyenv install ${PYTHON_VERSION} --force"
fi

# ── Step 4: Create launcher script ───────────────────────────────

mkdir -p "$(dirname "$LAUNCHER")"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Claude Code Menu Bar Monitor — launcher
# Generated by install.sh on $(date -Iseconds)
exec "${PYTHON_BIN}" "${SCRIPT_DIR}/claude_menubar.py" "\$@"
EOF
chmod +x "$LAUNCHER"
ok "Launcher created: ${LAUNCHER}"

# Check PATH
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    warn "$HOME/.local/bin is not in your PATH"
    echo "  Add this to your ~/.zshrc or ~/.bashrc:"
    echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# ── Step 5: Test the connection ──────────────────────────────────

echo ""
info "Testing API connection…"
"$PYTHON_BIN" "${SCRIPT_DIR}/claude_menubar.py" --test || true

# ── Step 6: Optionally install launchd auto-start ────────────────

echo ""
read -rp "$(printf '\033[1;34m▸\033[0m') Install as login item (auto-start at login)? [y/N] " INSTALL_LAUNCHD

if [[ "$INSTALL_LAUNCHD" =~ ^[Yy]$ ]]; then
    # Unload existing if present
    launchctl unload "$PLIST_PATH" 2>/dev/null || true

    cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.claude.menubar-monitor</string>
    <key>ProgramArguments</key>
    <array>
        <string>${PYTHON_BIN}</string>
        <string>${SCRIPT_DIR}/claude_menubar.py</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/claude-monitor.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/claude-monitor.err</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
    </dict>
</dict>
</plist>
EOF

    launchctl load "$PLIST_PATH"
    ok "Installed and started as login item"
    echo "  Plist: ${PLIST_PATH}"
    echo "  Logs:  /tmp/claude-monitor.log"
    echo ""
    echo "  To stop:    launchctl unload ${PLIST_PATH}"
    echo "  To restart: launchctl unload ${PLIST_PATH} && launchctl load ${PLIST_PATH}"
else
    ok "Skipped. Run manually with:  claude-monitor"
fi

# ── Done ─────────────────────────────────────────────────────────

echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  ✅  Claude Code Menu Bar Monitor installed!         │"
echo "│                                                      │"
echo "│  Commands:                                           │"
echo "│    claude-monitor              launch menu bar app   │"
echo "│    claude-monitor --test       test API connection   │"
echo "│    claude-monitor --add-profile NAME \"LABEL\"         │"
echo "│    claude-monitor --help       full usage info       │"
echo "└──────────────────────────────────────────────────────┘"